### ISSUE TITLE
Please add to package control

### ISSUE THREAD

**Issue by yyyc514** [manastech/sublime-crystal#9]

**Comment by pyros2097** [comment]
+1

**Comment by asterite** [comment]
One thing you could do is submit a pull request with [what's needed according to this page](https://packagecontrol.io/docs/submitting_a_package). Then we can merge it and do any necessary final steps. Sorry, but we are a bit out of time :-(

**Comment by pyros2097** [comment]
Done waiting for the pull request! :watch:

**Comment by asterite** [comment]
@pyros2097 Done merging the pull request and creating the `v0.0.1` tag. What's next?

**Comment by pyros2097** [comment]
Now We got to wait for the other pull request and keep our hands crossed :crossed_flags: . It might take a day or 2. Waiting :watch:!

I'll close this issue once its done

**Comment by daneb** [comment]
Ah! Waiting eagerly ;)

**Comment by pyros2097** [comment]
Its done try it out now. Now to improve the syntax like reserved words `and` and `or` are highlighted which made me think crystal supported them

**Comment by daneb** [comment]
Working like a dream, thanks @pyros2097

**Comment by asterite** [comment]
Indeed! @pyros2097 Thank you so much, this was requested for so long!
